language: node_js
node_js:
- '0.10'
before_script: chmod ugo+x ./deploy.sh
script: bash ./deploy.sh
env:
  global:
  - GH_REF: github.com/yang-wei/resit.git
  - secure: JEpA7/YCIGvoJJWmJZa2ku6cKAyiA5op+By1mCe9bDOKqDJu0OT5QEnF5akoQamZaGtqSKHdu3xx8PVvRKPTjXNwJ4wl23TSiY/v/waJbg8xlK3YLYBsxz2Q0tvMq1547WK0Epiw7LoZMxresx7tt4bnLkoyPYOSj/Jqixuo80ye8niwj7BqQ4wsv4LBTwbcVrg5F1NfQRtnuakYkvwur6kHo0TM2ex6EWvJd4MKYhWDzJZTkfiFlK8cb2wVATZB92woWv89nhpILJL9rq0nzXZO9Ba1uBeZfR01eQQvC+QioAHw0YYFlAvu13zeFqyayy94zGV/PzWemPQ+aAd6WgGyCH/RRwFR7Mk0fx8YSKlTij0m1gKXniscuVevK+emq6SOnjdKg+r4XjRElhY9ZJOaBlAjSOYPEe4fqQEhjGenQ4Atq/PP31G6P4zVgPKk9MxdoPWm5Tm2XO38lSe81xXYDvX2NSf4acY3wxTCV5H+HYkCUhLHEHEkoeGj0xON7BlY/TIb0FWS8xjJJ0kjRWi/RpCx2FMO3P1YqYoikQkUri0pYMhSwxYDv+3szQBemR+ykqpZDpNpkd7Sjkk3pHtC8VjoG1bD9ZSg//d7EwcMZGmIKmhxpAEjuSwTTu8x1K197CAHIM6hYi7ovIkTFaO2l7eOu40PNblzerUCX9Q=
