language: node_js
node_js:
  - "0.10"
env:
  global:
  - GH_REF: github.com/yang-wei/resit.git
  - secure: "J1VFVhtMH+86v0L/VhxStZdSCNHb5yoSkVOdMUjsXg3tGLJ0hkfuHn8Ho+/B2BeQNPNwDUg/V23cp0O20gqpBv8FUXRvuOzpD2trvVmttuAiqQwzXQ7S/ziUyUZJeRtOUeWPIt9EaKAsVnzoVDOoNlIaA4ItvROx4FLDw+oOHtAWIzFHrwhnbi8rXt6f57qdmg2Ps8rPihTMKuXXY+uYPmryGdcTFyew7iYE3JFSz2a+7IXOylDkTu0qRlcJ2RDFCOVtNBzuCa6fPW4ED5LAcq3ZdcNeIDWkh18DmH8oaFR5MnouTGVwxnbOmq/chzqPPFO+gWlD/vt7B4/rF5nLqPvdtNlbSIAdFJP1a0MYirOoReuK52P0usD36eW4D9AUbiH+WOY8EjPbHPyNpVl32lnGYahze3y8leYNgOXXc4Crr5Gc71jYOZNJYUpEqfVaGIflefpDG1ULKH7VJQxRifIIkcfZfNCwQavHfHa8ODeAUhNQOpcKFO9LuJH04um4t5+l+kdKDWEQHACP+UP9i3CRPV8e0jXZa71/jQAg72KaO6cbfAnoQEOccEBt96FJK9XZzHy9mtfQ2m5FMIVO6Cl7xVe161gUBCOfHE8UB+TI58kmnzKYF6Ld476VloTgPBTBtpiAzYk+AUtD8JZifpHR/x86kWF/AE5RZt5Y2Iw="
script: bash ./deploy.sh